export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const DB_CONNECTED = 'DB_CONNECTED'
export const DB_DISCONNECTED = 'DB_DISCONNECTED'
export const DB_RECONNECTED = 'DB_RECONNECTED'
export const SET_COLLECTIONS = 'SET_COLLECTIONS'
